steps:
  script:
    image: khs1994/node:git
    env:
      - APP_ID=${APP_ID}
    run: |
      npm config set cache /tmp/pcit_cache/npm

      export NODE_PATH=/usr/local/lib/node_modules

      npm -g i miniprogram-ci typescript \
        --registry https://registry.npm.taobao.org

      cd client && npm install --registry https://registry.npm.taobao.org && cd ..

      npm run gitbook:summary:generate
      npm run gitbook:summary:towxml

      npm run tsc:pro

      echo -e "${PRIVATE_KEY}" > private.${APP_ID}.key

      npm run npm:build

      npm run upload
